spring.application.name=testing-system

spring.datasource.url=jdbc:mysql://localhost:3306/dtn2601_testing_system
spring.datasource.username=root
spring.datasource.password=dong
spring.jpa.hibernate.ddl-auto=none
